common/models/Model.php
<?php

namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use yii\imagine\Image;
use Imagine\Image\ManipulatorInterface;

class Model extends ActiveRecord
{
    public $avatarFile;
    public $digitFile_1;
    public $digitFile_2;
    public $digitFile_3;
    public $digitFile_4;

    public static function tableName()
    {
        return '{{%model}}';
    }

    public function rules()
    {
        return [
            [['avatarFile'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
            [['digitFile_1'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
            [['digitFile_2'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
            [['digitFile_3'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
            [['digitFile_4'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
            [['avatar', 'city', 'instagram', 'phone', 'telegram', 'whatsapp', 'video', 'digit_1', 'digit_2', 'digit_3', 'digit_4'], 'string', 'max' => 255],
            [['pastClients'], 'string'],
            [[
              'userId',
              'categoryId',
              'gender',
              'hourPrice',
              'dayPrice',
              'age',
              'height',
              'weight',
              'shoes',
              'shirt',
              'bust',
              'ethnicity',
              'eyes',
              'hair',
              'tattoo',
              'isHiddenContacts',
              'tfp',
            ], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'userId' => 'Пользователь',
            'avatar' => 'Аватар',
            'categoryId' => 'Категория',
            'city' => 'Город',
            'gender' => 'Пол',
            'hourPrice' => 'Стоимость часа',
            'dayPrice' => 'Стоимость дня',
            'age' => 'Возраст',
            'height' => 'Рост',
            'weight' => 'Вес',
            'shoes' => 'Размер обуви',
            'shirt' => 'Размер одежды',
            'bust' => 'Размер груди',
            'ethnicity' => 'Тип лица',
            'eyes' => 'Цвет глаз',
            'hair' => 'Цвет волос',
            'tattoo' => 'Татуировки',
            'instagram' => 'Инстаграм',
            'phone' => 'Телефон',
            'telegram' => 'Телеграм',
            'whatsapp' => 'Whatsapp',
            'video' => 'Промо видео',
            'pastClients' => 'Последние места работы',
            'isHiddenContacts' => 'Скрыть ваши контакты?',
            'tfp' => 'Возможно ли TFP?',
        ];
    }


    private function checkDir($path = false)
    {
      $dir = Yii::getAlias('@upload/') . $this->userId;

      if ($path) {
        $dir .= '/' . $path;
      }

      if(!is_dir($dir)) {
        mkdir($dir, 0777, true);
      }
    }


    public function uploadAvatar()
    {
      if (is_object($this->avatarFile)) {
        $fileName = Yii::$app->security->generateRandomString(12) . '.' . $this->avatarFile->extension;

        $this->avatar = $fileName;

        $path = '@upload/';
        $imagePath = Yii::getAlias($path . 'all/' . $fileName);

        if ($this->avatarFile->saveAs($imagePath)) {
            // Yii::$app->imageOptimizer->optimize($imagePath);
            Yii::$app->imageOptimizer->deleteEXIFMetadata($imagePath);
        }

        $avatarPath = Yii::getAlias($path . 'avatars/' . $fileName); // 342x204

        if (Image::thumbnail($imagePath, 180, 180, ManipulatorInterface::THUMBNAIL_OUTBOUND)->save($avatarPath, ['quality' => 81])) {
            // Yii::$app->imageOptimizer->optimize($avatarPath);
        }

        return true;
      } else {
        return false;
      }
    }

    public function uploadDigits()
    {
      $digitFiles = [
        $this->digitFile_1,
        $this->digitFile_2,
        $this->digitFile_3,
        $this->digitFile_4,
      ];


      $this->checkDir();
      $this->checkDir('digits');

      if (is_array($digitFiles)) {
        foreach ($digitFiles as $key => $digitFile) {
          if (is_object($digitFile)) {
            $fileName = Yii::$app->security->generateRandomString(12) . '.' . $digitFile->extension;

            if ($key == 0) { $this->digit_1 = $fileName; }
            else if ($key == 1) { $this->digit_2 = $fileName; }
            else if ($key == 2) { $this->digit_3 = $fileName; }
            else if ($key == 3) { $this->digit_4 = $fileName; }

            $path = '@upload/' . $this->userId;
            $imagePath = Yii::getAlias($path . '/digits/' . $fileName);

            if ($digitFile->saveAs($imagePath)) {
                // Yii::$app->imageOptimizer->optimize($imagePath);
                Yii::$app->imageOptimizer->deleteEXIFMetadata($imagePath);
            }

          }
        }



        return true;
      } else {
        return false;
      }
    }

    public function getAvatarImage()
    {
      if(!is_null($this->avatar) AND !empty($this->avatar)) {
        return Yii::getAlias('/upload/avatars/' . $this->avatar);;
      }
      return '/img/placeholder@2x.png';
    }

    public function getDigit1Image()
    {
      if(!is_null($this->digit_1) AND !empty($this->digit_1)) {
        return Yii::getAlias('/upload/'.$this->userId.'/digits/' . $this->digit_1);;
      }
      return '/img/digit_1.jpg';
    }
    public function getDigit2Image()
    {
      if(!is_null($this->digit_2) AND !empty($this->digit_2)) {
        return Yii::getAlias('/upload/'.$this->userId.'/digits/' . $this->digit_2);;
      }
      return '/img/digit_2.jpg';
    }
    public function getDigit3Image()
    {
      if(!is_null($this->digit_3) AND !empty($this->digit_3)) {
        return Yii::getAlias('/upload/'.$this->userId.'/digits/' . $this->digit_3);;
      }
      return '/img/digit_3.jpg';
    }
    public function getDigit4Image()
    {
      if(!is_null($this->digit_4) AND !empty($this->digit_4)) {
        return Yii::getAlias('/upload/'.$this->userId.'/digits/' . $this->digit_4);;
      }
      return '/img/digit_4.jpg';
    }

    public function getImages()
    {
        return $this->hasMany(ModelImage::className(), ['modelId' => 'id']);
    }

    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'userId']);
    }

    public function getInstagramImages()
    {
        return $this->hasMany(InstagramImage::className(), ['userId' => 'userId']);
    }


    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created',
                'updatedAtAttribute' => 'updated',
                'value' => new Expression('NOW()'),
            ],
        ];
    }
}

common/models/User.php
<?php

namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * User model
 *
 * @property integer $id
 * @property string $name
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $verification_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 */
class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_DELETED = 0;
    const STATUS_INACTIVE = 1;
    const STATUS_ACTIVE = 2;
    const STATUS_NOT_CONFIRM = 3;

    const STATUS_EMPTY_MODEL = 4;
    const STATUS_EMPTY_PHOTOGRAPHER = 5;
    const STATUS_EMPTY_COMPANY = 6;

    const STATUS_FILLED_MODEL = 7;
    const STATUS_FILLED_PHOTOGRAPHER = 8;
    const STATUS_FILLED_COMPANY = 9;


    const TYPE_MODEL = 0;
    const TYPE_PHOTOGRAPHER = 1;
    const TYPE_COMPANY = 2;

    public static function typeLabels()
    {
        return [
            self::TYPE_MODEL        => 'Модель',
            self::TYPE_PHOTOGRAPHER => 'Фотограф',
            self::TYPE_COMPANY      => 'Компания',
        ];
    }

    public static function typeSlug()
    {
        return [
            self::TYPE_MODEL        => 'model',
            self::TYPE_PHOTOGRAPHER => 'photographer',
            self::TYPE_COMPANY      => 'company',
        ];
    }

    public static function statusLabels()
    {
        return [
            self::STATUS_ACTIVE              => 'Активен',
            self::STATUS_INACTIVE            => 'Не активен',
            self::STATUS_DELETED             => 'Удален',
            self::STATUS_NOT_CONFIRM         => 'Не подтвержден',
            self::STATUS_EMPTY_MODEL         => 'Пустая модель',
            self::STATUS_EMPTY_PHOTOGRAPHER  => 'Пустой фотограф',
            self::STATUS_FILLED_MODEL        => 'Заполненная модель',
            self::STATUS_FILLED_PHOTOGRAPHER => 'Заполненный фотограф',
        ];
    }


    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'surname'], 'string', 'max' => 255],
            ['type', 'integer'],
            ['status', 'default', 'value' => self::STATUS_NOT_CONFIRM],
            // ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_INACTIVE, self::STATUS_DELETED]],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id]);
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    public static function findByEmail($email)
    {
        return static::findOne(['email' => $email]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            // 'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds user by verification email token
     *
     * @param string $token verify email token
     * @return static|null
     */
    public static function findByVerificationToken($token) {
        return static::findOne([
            'verification_token' => $token,
            'status' => self::STATUS_INACTIVE
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return bool
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Generates new token for email verification
     */
    public function generateEmailVerificationToken()
    {
        $this->verification_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    public function getEntity()
    {
      if ($this->type == User::TYPE_MODEL) {
        $model = Model::find()->where(['userId' => $this->id])->one();
        if(!is_object($model)) {
          $model = new Model();
          $model->userId = $this->id;
          $model->save();
        }
      } else if ($this->type == User::TYPE_PHOTOGRAPHER) {
        $model = Photographer::find()->where(['userId' => $this->id])->one();
        if(!is_object($model)) {
          $model = new Photographer();
          $model->userId = $this->id;
          $model->save();
        }
      } else if ($this->type == User::TYPE_COMPANY) {

      }
      return $model;
    }

    public function getFavorites()
    {
      return $this->hasMany(Favorite::className(), ['userId' => 'id']);
    }


    public function getNotifications()
    {
      $notifications = Notification::find()->where(['recipientUserId' => $this->id])->orderBy(['id' => SORT_DESC])->all();
      foreach ($notifications as $notification) {
        if($notification->isRead == false) {
          $notification->isRead = true;
          $notification->save();
        }
      }
      return $notifications;
    }

    public function getIsUnreadNotifications()
    {
      return is_object(Notification::find()->where(['recipientUserId' => $this->id])->andWhere(['isRead' => false])->one()) ? true :false;
    }

    public function getInstagramToken()
    {
      $token = InstagramToken::find()->where(['userId' => $this->id])->one();
      if (is_object($token)) {
        return $token;
      }
      return false;
    }

    public function hasInstagramToken()
    {
      return is_object($this->instagramToken) ? ( !is_null($this->instagramToken->token) ? true : false ) : false;
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Имя',
            'surname' => 'Фамилия',
            'email' => 'Email',
        ];
    }
}

frontend/views/layouts/_footer.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
?>

<footer class="main-footer">

    <div class="wrap">
      <!-- <div class="footer-item">
        <h3>Заголовок</h3>
        <a href="#">Link</a>
        <a href="#">Link</a>
        <a href="#">Link</a>
        <a href="#">Link</a>
      </div>

      <div class="footer-item">
        <h3>Заголовок</h3>
        <a href="#">Link</a>
        <a href="#">Link</a>
        <a href="#">Link</a>
      </div>

      <div class="footer-item">
        <h3>Заголовок</h3>
        <a href="#">Link</a>
        <a href="#">Link</a>
        <a href="#">Link</a>
      </div>

      <div class="footer-item">
        <h3>Заголовок</h3>
        <a href="#">Link</a>
        <a href="#">Link</a>
      </div> -->
    </div>

    <div class="main-footer__bottom">
      <span>2021 © Modelista Inc.</span>
      <span>All Rights Reserved</span>
    </div>
    <?= $this->render('_social-list') ?>

</footer>

frontend/views/layouts/_gallery.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
?>

<div class="gallery" id="gallery">

  <a href="#" class="gallery__close js-gallery-close">
    <svg _ngcontent-c54="" class="icon" height="32" width="32" xmlns="http://www.w3.org/2000/svg"><g _ngcontent-c54="" fill="none" fill-rule="evenodd" stroke="currentColor" stroke-width="2"><path _ngcontent-c54="" d="M8 8l16.986 16.986M19 14l6-6-6 6zM8 26l9-9"></path></g></svg>
  </a>

  <div class="gallery__content-wrap">
    <div class="gallery__content">

      <div class="gallery-container">
        <div class="gallery-image">

          <div class="gallery-control _left js-gallery-left _active">
            <div class="ico">
              <svg _ngcontent-c29="" class="icon" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><g _ngcontent-c29="" fill="none" fill-rule="evenodd" stroke="currentColor" stroke-linecap="square" stroke-width="2"><path _ngcontent-c29="" d="M12.378 23.788l8-8M17.33 12.901l-4.952-4.69"></path></g></svg>
            </div>
          </div>

          <div class="gallery-control _right js-gallery-right _active">
            <div class="ico">
              <svg _ngcontent-c29="" class="icon" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><g _ngcontent-c29="" fill="none" fill-rule="evenodd" stroke="currentColor" stroke-linecap="square" stroke-width="2"><path _ngcontent-c29="" d="M12.378 23.788l8-8M17.33 12.901l-4.952-4.69"></path></g></svg>
            </div>
          </div>

          <div class="gallery-preview">
            <img class="_image" src="" alt="">
          </div>

        </div>
        <div class="gallery-progress">
          <span><span class="_imagePosition"></span> из <span class="_imagesCount"></span></span>
        </div>
      </div>

      <div class="gallery-footer">
        <div class="gallery-info">
          <h3 class="gallery-info__name"><a href="#" class="_link _name" target="_blank"></a></h3>
          <span class="gallery-info__text _location"></span>
          <span class="gallery-info__text _price"></span>
        </div>
      </div>

    </div>
    <div class="gallery__content-right">
      <h3>Детали</h3>
      <div class="gallery-stats">
        <div class="gallery-stat-item">
          <h4>Рост</h4>
          <span class="_height"></span>
        </div>
        <div class="gallery-stat-item">
          <h4>Вес</h4>
          <span class="_weight"></span>
        </div>
        <div class="gallery-stat-item">
          <h4>Возраст</h4>
          <span class="_age"></span>
        </div>
        <div class="gallery-stat-item">
          <h4>Размер обуви</h4>
          <span class="_shoes"></span>
        </div>
        <div class="gallery-stat-item">
          <h4>Размер одежды</h4>
          <span class="_shirt"></span>
        </div>
        <div class="gallery-stat-item">
          <h4>Размер груди</h4>
          <span class="_bust"></span>
        </div>
        <div class="gallery-stat-item">
          <h4>Тип лица</h4>
          <span class="_ethnicity"></span>
        </div>
        <div class="gallery-stat-item">
          <h4>Цвет глаз</h4>
          <span class="_eyes"></span>
        </div>
        <div class="gallery-stat-item">
          <h4>Цвет волос</h4>
          <span class="_hair"></span>
        </div>
      </div>
    </div>
  </div>

</div>

frontend/views/layouts/_header.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

$user = Yii::$app->user->identity;
?>

<header class="main-header">
  <a href="/" class="logo main-logo">Modelista</a>


  <?php if (Url::to() != '/'): ?>
    <div class="main-header__center-menu">
      <a href="/browse" class="<?= (Url::to() == '/browse') ? '_active' : '' ?>">Модели</a>
      <a href="/browse/photographers" class="<?= (Url::to() == '/browse/photographers') ? '_active' : '' ?>">Фотографы</a>
      <?php if (!Yii::$app->user->isGuest): ?>
        <a href="/browse/locations" class="<?= (Url::to() == '/browse/locations') ? '_active' : '' ?>">Локации</a>
        <a href="/favorite" class="<?= (Url::to() == '/favorite') ? '_active' : '' ?>">Избранное</a>
      <?php endif; ?>
    </div>
  <?php endif; ?>


  <a href="#" class="menu-btn js-menu">
    <span></span>
    <span></span>
    <span></span>
  </a>

  <div class="main-menu-container js-main-menu">

    <?php if (Url::to() == '/'): ?>

      <a href="#model" class="site-menu-btn js-nav-scroll">Для моделей</a>
      <a href="#photographer" class="site-menu-btn js-nav-scroll">Для фотографов</a>
      <a href="#company" class="site-menu-btn js-nav-scroll">Компаниям</a>
      <a href="/browse" class="site-menu-btn browse-btn">База моделей</a>
      <?php if (Yii::$app->user->isGuest): ?>
        <a href="/auth" class="site-menu-btn login-btn">Войти</a>
        <a href="/auth/register" class="site-menu-btn signup-btn">Регистрация</a>
      <?php endif; ?>

    <?php else: ?>

          <div class="main-header__center-menu-mobile">
            <a href="/browse">Модели</a>
            <a href="/browse/photographers">Фотографы</a>
            <?php if (!Yii::$app->user->isGuest): ?>
              <a href="/browse/locations">Локации</a>
              <a href="/favorite">Избранное</a>
            <?php endif; ?>
          </div>

      <?php if (Yii::$app->user->isGuest): ?>
        <a href="/auth">Войти</a>
        <a href="/auth/register" class="signup">Регистрация</a>
      <?php endif; ?>
    <?php endif; ?>

    <?php if (!Yii::$app->user->isGuest): ?>
      <div class="main-header__actions">
        <a href="#" class="action-link js-show-notification-center <?= $user->isUnreadNotifications ? '_new' : '' ?>" title="Уведомления">
          <svg class="Icon__icon--2u9lI HeaderItemNotifications__icon--sTRyK" width="18" height="22" xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd"><path stroke="currentColor" d="M2.70711 12.7071L3 12.4142V9c0-3.31371 2.68629-6 6-6 3.3137 0 6 2.68629 6 6v3.4142l.2929.2929L17 14.4142V17H1v-2.5858l1.70711-1.7071z" stroke-width="2"></path><path fill="currentColor" d="M6 19c0 1.65674 1.38379 3 3.09082 3 1.70703 0 3.09082-1.34326 3.09082-3h-2c0 .496338-.43164 1-1.09082 1C8.43164 20 8 19.496338 8 19H6z"></path><path stroke="currentColor" fill="currentColor" d="M9.5 1.5c0 .55228-.44772 1-1 1-.552285 0-1-.44772-1-1 0-.552285.447715-1 1-1 .55228 0 1 .447715 1 1z" fill-rule="nonzero"></path></g></svg>
        </a>
        <a href="/profile" class="main-user-ico" title="Профиль">
          <div class="img" style="background-image: url(<?= $user->entity->avatarImage ?>);background-position: center;background-size: cover;"></div>
        </a>

      </div>
    <?php endif; ?>

  </div>

  <?php if (!Yii::$app->user->isGuest): ?>
    <?= $this->render('_notification-center') ?>
  <?php endif; ?>

</header>

frontend/views/layouts/_modals.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

?>


<div class="modal">

  <div class="modal-container">
    <div class="modal-container__header">
      <h3>Контакты модели</h3>
      <a href="#" class="modal__close js-close-modal">
        <svg _ngcontent-c44="" class="icon" height="32" width="32" xmlns="http://www.w3.org/2000/svg"><g _ngcontent-c44="" fill="none" fill-rule="evenodd" stroke="currentColor" stroke-width="2"><path _ngcontent-c44="" d="M8 8l16.986 16.986M19 14l6-6-6 6zM8 26l9-9"></path></g></svg>
      </a>
    </div>
    <div class="modal-container__content">


    </div>
  </div>

</div>

frontend/views/layouts/_notification-center.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use common\models\User;
use common\models\Notification;
use common\models\ContactRequest;

$user = Yii::$app->user->identity;
?>


<div class="notification-center">

  <div class="notification-center__header">
    <h3>Последние уведомления</h3>
  </div>

  <a href="#" class="notification-center__close js-notification-center-close">
    <svg _ngcontent-c54="" class="icon" height="32" width="32" xmlns="http://www.w3.org/2000/svg"><g _ngcontent-c54="" fill="none" fill-rule="evenodd" stroke="currentColor" stroke-width="2"><path _ngcontent-c54="" d="M8 8l16.986 16.986M19 14l6-6-6 6zM8 26l9-9"></path></g></svg>
  </a>

  <div class="notification-center__content">

    <?php if (sizeof($user->notifications) < 1): ?>

      <div class="empty">
        Тут ничего нет ;(
      </div>

    <?php else: ?>


      <?php foreach ($user->notifications as $notification): ?>
        <?php
          $sender = $notification->sender;
          $senderType = ($sender->type == User::TYPE_MODEL) ? 0 : ($sender->type == User::TYPE_PHOTOGRAPHER) ? 1 : 0;
          $senderLabel = (($senderType == 0) ? 'Модель' : (($senderType == 1) ? 'Фотограф' : 'Модель')) . ' <a href="/'. (($senderType == 0) ? 'model' : (($senderType == 1) ? 'photographer' : 'model')).'/'. $sender->entity->id .'" target="_blank">'.$sender->name.' '. $sender->surname .'</a>';
        ?>

        <?php if ($notification->type == Notification::TYPE_CONTACT_REQUEST): ?>

          <div class="notification">
            <div class="notification__header">
              <span><?= $senderLabel ?> просит доступ к вашим контактам</span>
            </div>
            <div class="notification__actions">
              <a href="#" class="btn light-btn js-notification-contact-btn _deny" data-id="<?= $notification->id ?>">
                <?php if ($notification->contactRequest->status == ContactRequest::STATUS_DENIED): ?>
                  Отклонено
                <?php else: ?>
                  Отклонить
                <?php endif; ?>
              </a>
              <a href="#" class="btn js-notification-contact-btn _accept" data-id="<?= $notification->id ?>">
                <?php if ($notification->contactRequest->status == ContactRequest::STATUS_ACCEPTED): ?>
                  Принято
                <?php else: ?>
                  Принять
                <?php endif; ?>
              </a>
            </div>
          </div>

        <?php elseif ($notification->type == Notification::TYPE_ACCEPTED_CONTACT_REQUEST): ?>

          <div class="notification">
            <div class="notification__header">
              <span><?= $senderLabel ?> принял(а) ваш запрос на контакты</span>
            </div>
            <div class="notification__actions">
              <a href="/<?= (($senderType == 0) ? 'model' : (($senderType == 1) ? 'photographer' : 'model')).'/'. $sender->entity->id ?>" target="_blank" class="btn light-btn">Профиль</a>
              <a href="#" class="btn js-show-contact" data-id="<?= $sender->entity->id ?>" data-type="<?= $sender->type ?>">Контакты</a>
            </div>
          </div>

        <?php elseif ($notification->type == Notification::TYPE_DENIED_CONTACT_REQUEST): ?>

          <div class="notification">
            <div class="notification__header">
              <span><?= $senderLabel ?> отклонил(а) ваш запрос на контакты</span>
            </div>
          </div>

        <?php endif; ?>


      <?php endforeach; ?>


    <?php endif; ?>


  </div>

</div>

frontend/views/layouts/_site-footer.php
<div class="site-footer">
  <div class="container">
    <div class="site-footer__inner">
      <div class="copyright">2021 © Modelista Inc.</div>
      <?= $this->render('_social-list') ?>
    </div>
  </div>
</div>