backend/models/LoginForm.php
<?php

namespace backend\models;

use Yii;
use yii\base\Model;
use common\models\Admin;

/**
 * Login form
 */
class LoginForm extends Model
{
    public $username;
    public $password;
    public $rememberMe = true;

    private $_user;


    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            // username and password are both required
            [['username', 'password'], 'required'],
            // rememberMe must be a boolean value
            ['rememberMe', 'boolean'],
            // password is validated by validatePassword()
            ['password', 'validatePassword'],
        ];
    }

    /**
     * Validates the password.
     * This method serves as the inline validation for password.
     *
     * @param string $attribute the attribute currently being validated
     * @param array $params the additional name-value pairs given in the rule
     */
    public function validatePassword($attribute, $params)
    {
        if (!$this->hasErrors()) {
            $user = $this->getUser();
            if (!$user || !$user->validatePassword($this->password)) {
                $this->addError($attribute, 'Incorrect username or password.');
            }
        }
    }

    /**
     * Logs in a user using the provided username and password.
     *
     * @return bool whether the user is logged in successfully
     */
    public function login()
    {

        if ($this->validate()) {
            return Yii::$app->user->login($this->getUser(), $this->rememberMe ? 3600 * 24 * 30 : 0);
        }

        return false;
    }

    /**
     * Finds user by [[username]]
     *
     * @return User|null
     */
    protected function getUser()
    {
        if ($this->_user === null) {
            $this->_user = Admin::findByUsername($this->username);
        }

        return $this->_user;
    }
}

common/models/ContactRequest.php
<?php

namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use yii\imagine\Image;
use Imagine\Image\ManipulatorInterface;

class ContactRequest extends ActiveRecord
{

    const STATUS_NEW = 0;
    const STATUS_ACCEPTED = 1;
    const STATUS_DENIED = 2;

    public static function statusLabels()
    {
        return [
            self::STATUS_NEW      => 'Новый',
            self::STATUS_ACCEPTED => 'Принятый',
            self::STATUS_DENIED   => 'Отклоненный',
        ];
    }

    public static function tableName()
    {
        return '{{%contact_request}}';
    }

    public function rules()
    {
        return [
            [['senderUserId', 'recipientUserId'], 'integer'],
            [['status'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'senderUserId' => 'Отправитель',
            'recipientUserId' => 'Получатель',
            'status' => 'Статус',
        ];
    }


    public function getSender()
    {
        return $this->hasOne(User::className(), ['id' => 'senderUserId']);
    }

    public function getRecipient()
    {
        return $this->hasOne(User::className(), ['id' => 'recipientUserId']);
    }



    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created',
                'updatedAtAttribute' => 'updated',
                'value' => new Expression('NOW()'),
            ],
        ];
    }
}

common/models/Data.php
<?php
namespace common\models;

use Yii;

class Data {


  const CITIES = [
    'msc' => 'Москва',
    'spb' => 'Санкт-Петербург',
    'other' => 'Другой город',
  ];

  const GENDER = [
    0 => 'Женщина',
    1 => 'Мужчина',
    2 => 'Non-binary',
  ];

  const CATEGORIES = [
    0 => [
      'title' => 'Beauty',
      'image' => 'beauty.jpg'
    ],
    1 => [
      'title' => 'Lifestyle',
      'image' => 'lifestyle.jpg'
    ],
    2 => [
      'title' => 'E-Comm',
      'image' => 'e-comm.jpg'
    ],
    3 => [
      'title' => 'Curve',
      'image' => 'curve.jpg'
    ],
    4 => [
      'title' => 'Unique',
      'image' => 'unique.jpg'
    ],
    5 => [
      'title' => 'Fitness',
      'image' => 'fitness.jpg'
    ],
    6 => [
      'title' => 'Swimwear',
      'image' => 'swimwear.jpg'
    ],
    7 => [
      'title' => 'Influencer',
      'image' => 'influencer.jpg'
    ],
  ];

  const ETHNICITY = [
    'Азиатский',
    'Афроамериканский',
    'Европейский',
    'Кавказский',
    'Латинский ',
  ];


  const EYES = [
    'Голубые',
    'Карие',
    'Зеленые',
    'Серые',
    'Черные',
    'Другие',
  ];

  const HAIR = [
    'Блондин(-ка)',
    'Брюнет(-ка)',
    'Шатен(-ка)',
    'Рыжий(-ая)',
    'Седой(-ая)',
    'Другой',
  ];

  const TATTOO = [
    0 => 'Нет',
    1 => 'Есть',
  ];

}

common/models/InstagramImage.php
<?php

namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use yii\imagine\Image;
use Imagine\Image\ManipulatorInterface;

class InstagramImage extends ActiveRecord
{
    public static function tableName()
    {
        return '{{%instagram_image}}';
    }

    public function rules()
    {
        return [
            [['image', 'caption', 'permalink', 'username', 'timestamp', 'instagramImageId'], 'string'],
            [['userId'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'userId' => 'Пользователь',
        ];
    }


    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'userId']);
    }

    public function getImageWithPath()
    {
      return '/upload/'.$this->userId.'/instagram/' . $this->image;
      // return Yii::getAlias('@upload/all/' . $this->image);
    }


    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created',
                'updatedAtAttribute' => 'updated',
                'value' => new Expression('NOW()'),
            ],
        ];
    }
}

common/models/Model.php
<?php

namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use yii\imagine\Image;
use Imagine\Image\ManipulatorInterface;

class Model extends ActiveRecord
{
    public $avatarFile;
    public $digitFile_1;
    public $digitFile_2;
    public $digitFile_3;
    public $digitFile_4;

    public static function tableName()
    {
        return '{{%model}}';
    }

    public function rules()
    {
        return [
            [['avatarFile'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
            [['digitFile_1'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
            [['digitFile_2'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
            [['digitFile_3'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
            [['digitFile_4'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
            [['avatar', 'city', 'instagram', 'phone', 'telegram', 'whatsapp', 'video', 'digit_1', 'digit_2', 'digit_3', 'digit_4'], 'string', 'max' => 255],
            [['pastClients'], 'string'],
            [[
              'userId',
              'categoryId',
              'gender',
              'hourPrice',
              'dayPrice',
              'age',
              'height',
              'weight',
              'shoes',
              'shirt',
              'bust',
              'ethnicity',
              'eyes',
              'hair',
              'tattoo',
              'isHiddenContacts',
              'tfp',
            ], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'userId' => 'Пользователь',
            'avatar' => 'Аватар',
            'categoryId' => 'Категория',
            'city' => 'Город',
            'gender' => 'Пол',
            'hourPrice' => 'Стоимость часа',
            'dayPrice' => 'Стоимость дня',
            'age' => 'Возраст',
            'height' => 'Рост',
            'weight' => 'Вес',
            'shoes' => 'Размер обуви',
            'shirt' => 'Размер одежды',
            'bust' => 'Размер груди',
            'ethnicity' => 'Тип лица',
            'eyes' => 'Цвет глаз',
            'hair' => 'Цвет волос',
            'tattoo' => 'Татуировки',
            'instagram' => 'Инстаграм',
            'phone' => 'Телефон',
            'telegram' => 'Телеграм',
            'whatsapp' => 'Whatsapp',
            'video' => 'Промо видео',
            'pastClients' => 'Последние места работы',
            'isHiddenContacts' => 'Скрыть ваши контакты?',
            'tfp' => 'Возможно ли TFP?',
        ];
    }


    private function checkDir($path = false)
    {
      $dir = Yii::getAlias('@upload/') . $this->userId;

      if ($path) {
        $dir .= '/' . $path;
      }

      if(!is_dir($dir)) {
        mkdir($dir, 0777, true);
      }
    }


    public function uploadAvatar()
    {
      if (is_object($this->avatarFile)) {
        $fileName = Yii::$app->security->generateRandomString(12) . '.' . $this->avatarFile->extension;

        $this->avatar = $fileName;

        $path = '@upload/';
        $imagePath = Yii::getAlias($path . 'all/' . $fileName);

        if ($this->avatarFile->saveAs($imagePath)) {
            // Yii::$app->imageOptimizer->optimize($imagePath);
            Yii::$app->imageOptimizer->deleteEXIFMetadata($imagePath);
        }

        $avatarPath = Yii::getAlias($path . 'avatars/' . $fileName); // 342x204

        if (Image::thumbnail($imagePath, 180, 180, ManipulatorInterface::THUMBNAIL_OUTBOUND)->save($avatarPath, ['quality' => 81])) {
            // Yii::$app->imageOptimizer->optimize($avatarPath);
        }

        return true;
      } else {
        return false;
      }
    }

    public function uploadDigits()
    {
      $digitFiles = [
        $this->digitFile_1,
        $this->digitFile_2,
        $this->digitFile_3,
        $this->digitFile_4,
      ];


      $this->checkDir();
      $this->checkDir('digits');

      if (is_array($digitFiles)) {
        foreach ($digitFiles as $key => $digitFile) {
          if (is_object($digitFile)) {
            $fileName = Yii::$app->security->generateRandomString(12) . '.' . $digitFile->extension;

            if ($key == 0) { $this->digit_1 = $fileName; }
            else if ($key == 1) { $this->digit_2 = $fileName; }
            else if ($key == 2) { $this->digit_3 = $fileName; }
            else if ($key == 3) { $this->digit_4 = $fileName; }

            $path = '@upload/' . $this->userId;
            $imagePath = Yii::getAlias($path . '/digits/' . $fileName);

            if ($digitFile->saveAs($imagePath)) {
                // Yii::$app->imageOptimizer->optimize($imagePath);
                Yii::$app->imageOptimizer->deleteEXIFMetadata($imagePath);
            }

          }
        }



        return true;
      } else {
        return false;
      }
    }

    public function getAvatarImage()
    {
      if(!is_null($this->avatar) AND !empty($this->avatar)) {
        return Yii::getAlias('/upload/avatars/' . $this->avatar);;
      }
      return '/img/placeholder@2x.png';
    }

    public function getDigit1Image()
    {
      if(!is_null($this->digit_1) AND !empty($this->digit_1)) {
        return Yii::getAlias('/upload/'.$this->userId.'/digits/' . $this->digit_1);;
      }
      return '/img/digit_1.jpg';
    }
    public function getDigit2Image()
    {
      if(!is_null($this->digit_2) AND !empty($this->digit_2)) {
        return Yii::getAlias('/upload/'.$this->userId.'/digits/' . $this->digit_2);;
      }
      return '/img/digit_2.jpg';
    }
    public function getDigit3Image()
    {
      if(!is_null($this->digit_3) AND !empty($this->digit_3)) {
        return Yii::getAlias('/upload/'.$this->userId.'/digits/' . $this->digit_3);;
      }
      return '/img/digit_3.jpg';
    }
    public function getDigit4Image()
    {
      if(!is_null($this->digit_4) AND !empty($this->digit_4)) {
        return Yii::getAlias('/upload/'.$this->userId.'/digits/' . $this->digit_4);;
      }
      return '/img/digit_4.jpg';
    }

    public function getImages()
    {
        return $this->hasMany(ModelImage::className(), ['modelId' => 'id']);
    }

    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'userId']);
    }

    public function getInstagramImages()
    {
        return $this->hasMany(InstagramImage::className(), ['userId' => 'userId']);
    }


    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created',
                'updatedAtAttribute' => 'updated',
                'value' => new Expression('NOW()'),
            ],
        ];
    }
}

common/models/ModelImage.php
<?php

namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use yii\imagine\Image;
use Imagine\Image\ManipulatorInterface;

class ModelImage extends ActiveRecord
{

    public static function tableName()
    {
        return '{{%model_image}}';
    }

    public function rules()
    {
        return [
            [['image'], 'string', 'max' => 255],
            [['modelId'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'modelId' => 'Модель',
            'image' => 'Изображение',
        ];
    }

    public function getModel()
    {
        return $this->hasOne(Model::className(), ['id' => 'modelId']);
    }

    public function getImageWithPath()
    {
      return '/upload/'.$this->model->userId.'/' . $this->image;
      // return Yii::getAlias('@upload/all/' . $this->image);
    }

    public function getImageThumbWithPath()
    {
      return '/upload/'.$this->model->userId.'/thumbnails/' . $this->image;
      // return Yii::getAlias('@upload/all/' . $this->image);
    }


    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created',
                'updatedAtAttribute' => 'updated',
                'value' => new Expression('NOW()'),
            ],
        ];
    }
}

backend/controllers/ModelController.php
<?php

namespace backend\controllers;

use common\models\User;
use common\models\search\ModelSearch;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\HttpException;
use yii\web\Controller;

class ModelController extends Controller
{
    /**
     * @var boolean whether to enable CSRF validation for the actions in this controller.
     * CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
     */
    public $enableCsrfValidation = false;

    public $baseUrl = '/admin/model';

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'create', 'update', 'delete'],
                        'roles' => ['@']
                    ]
                ]
            ]
        ];
    }



    public function actionIndex()
    {
        $searchModel = new ModelSearch;
        $dataProvider = $searchModel->search($_GET);

        Url::remember();
        \Yii::$app->session[ '__crudReturnUrl' ] = null;

        return $this->render(
            'index',
            [
                'dataProvider' => $dataProvider,
                'searchModel' => $searchModel,
            ]
        );
    }

    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new HttpException(404, 'The requested page does not exist.');
        }
    }

    public function actionCreate()
    {
        $model = new User;

        try {
            if ($model->load($_POST) && $model->save()) {
                return $this->redirect($this->baseUrl);
            } elseif (!\Yii::$app->request->isPost) {
                $model->load($_GET);
            }
        } catch (\Exception $e) {
            $msg = (isset($e->errorInfo[ 2 ])) ? $e->errorInfo[ 2 ] : $e->getMessage();
            $model->addError('_exception', $msg);
        }
        return $this->render('create', ['model' => $model]);
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load($_POST) && $model->save()) {
            return $this->redirect($this->baseUrl);
        } else {
            return $this->render(
                'update',
                [
                    'model' => $model,
                ]
            );
        }
    }

    public function actionDelete($id)
    {
        try {
            $this->findModel($id)->delete();
        } catch (\Exception $e) {
            $msg = (isset($e->errorInfo[ 2 ])) ? $e->errorInfo[ 2 ] : $e->getMessage();
            \Yii::$app->getSession()->setFlash('error', $msg);
            return $this->redirect($this->baseUrl);
        }
        return $this->redirect(['index']);
    }
}

frontend/views/model/_contact-data.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use common\models\User;
?>

<div class="contact-data">

  <?php if ($user->status != User::STATUS_ACTIVE): ?>
    <div class="not-allowed">
      <h3>Почти готово</h3>
      <p>Спасибо за регистрацию в Modelista. Ваша учетная запись находится на рассмотрении. Вы сможете связаться с моделями, как только ваша учетная запись будет одобрена.</p>
    </div>
  <?php else: ?>

    <?php if ($model->isHiddenContacts AND !$checkRequest): ?>
      <div class="contact-request">
        <p>Контакты этого профиля скрыты. Хотите отправить запрос, чтобы получить их?</p>
        <a href="#" class="btn js-send-request" data-id="<?= $model->user->id ?>">Да, хочу получить</a>
      </div>
    <?php else: ?>

      <?php if (!empty($model->instagram) AND !is_null($model->instagram)): ?>
        <div class="contact-row">
          <div class="contact-row__title">Инстаграм</div>
          <div class="contact-row__value"><?= $model->instagram ?></div>
        </div>
      <?php endif; ?>

      <?php if (!empty($model->telegram) AND !is_null($model->telegram)): ?>
        <div class="contact-row">
          <div class="contact-row__title">Телеграм</div>
          <div class="contact-row__value"><?= $model->telegram ?></div>
        </div>
      <?php endif; ?>

      <div class="contact-row">
        <div class="contact-row__title">Почта</div>
        <div class="contact-row__value"><?= $model->user->email ?></div>
      </div>

      <?php if (!empty($model->phone) AND !is_null($model->phone)): ?>
        <div class="contact-row">
          <div class="contact-row__title">Телефон</div>
          <div class="contact-row__value"><?= $model->phone ?></div>
        </div>
      <?php endif; ?>

      <?php if (!empty($model->whatsapp) AND !is_null($model->whatsapp)): ?>
        <div class="contact-row">
          <div class="contact-row__title">Whatsapp</div>
          <div class="contact-row__value"><?= $model->whatsapp ?></div>
        </div>
      <?php endif; ?>

    <?php endif; ?>


  <?php endif; ?>

</div>

frontend/views/model/_model-small-item.php
<?php
use common\models\Data;
use common\models\User;
use common\helpers\FormatHelper;

$model = $model->entity;
$modelUser = $model->user;
$modelName = $modelUser->name . ' ' . $modelUser->surname;

if ($modelUser->type == User::TYPE_MODEL) {
  $modelUrl = '/model/';
} else if ($modelUser->type == User::TYPE_PHOTOGRAPHER) {
  $modelUrl = '/photographer/';
}
$modelUrl .= $model->id;
?>

<div class="small-item">
  <div class="small-item__images">

    <!-- <a href="#" class="small-item__slider-arrow _left js-small-item-slider-prev">
      <svg _ngcontent-c29="" class="icon" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><g _ngcontent-c29="" fill="none" fill-rule="evenodd" stroke="currentColor" stroke-linecap="square" stroke-width="2"><path _ngcontent-c29="" d="M12.378 23.788l8-8M17.33 12.901l-4.952-4.69"></path></g></svg>
    </a>

    <a href="#" class="small-item__slider-arrow _right js-small-item-slider-next">
      <svg _ngcontent-c29="" class="icon" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><g _ngcontent-c29="" fill="none" fill-rule="evenodd" stroke="currentColor" stroke-linecap="square" stroke-width="2"><path _ngcontent-c29="" d="M12.378 23.788l8-8M17.33 12.901l-4.952-4.69"></path></g></svg>
    </a> -->

    <div class="small-item__slider js-small-item-slider">
      <?php $counter = 0; ?>
      <?php foreach ($model->images as $key => $image): ?>
        <?php if ($counter > 7) { break; } ?>
        <div class="small-item__photo">
          <div class="photo">
            <img data-src="<?= $image->imageThumbWithPath ?>" class="lazyload" />
          </div>
        </div>
        <?php $counter++; ?>
      <?php endforeach; ?>
    </div>

  </div>
  <div class="small-item__content">
    <div class="main-details">
      <div class="main-details__top">
        <a href="<?= $modelUrl ?>" title="<?= $modelName ?>" class="name"><?= $modelName ?></a>
        <a href="#" class="favorite js-favorite-btn" data-id="<?= $model->id ?>" data-type="<?= $modelUser->type ?>">
          <svg class="Icon__icon--2u9lI" xmlns="http://www.w3.org/2000/svg" width="21" height="18" viewBox="0 0 20 18"><g fill-rule="nonzero" fill="none"><path fill="#222" fill-opacity=".09" fill-rule="evenodd" stroke="currentColor" stroke-opacity=".15" d="M10 3.087c1.612-1.803 4.088-2.5 6.25-1.85C18.531 1.923 20 3.94 20 6.816c0 1.447-.547 2.903-1.563 4.353-.859 1.227-2.03 2.417-3.437 3.555a30.715 30.715 0 0 1-3.438 2.397c-.41.248-.792.466-1.132.652l-.195.105-.235.125-.235-.125a29.68 29.68 0 0 1-1.328-.757A30.72 30.72 0 0 1 5 14.724c-1.406-1.138-2.578-2.328-3.438-3.555C.547 9.72 0 8.263 0 6.816 0 3.94 1.469 1.923 3.75 1.237c2.162-.65 4.638.047 6.25 1.85z"></path></g></svg>
        </a>
      </div>
      <div class="main-details__location">
        <?= Data::CITIES[ $model->city ] ?>
      </div>
    </div>
    <div class="small-item__actions">
      <a href="<?= $modelUrl ?>" title="<?= $modelName ?>" class="btn border-btn">Портфолио</a>
      <a href="#" class="btn js-show-contact" data-id="<?= $model->id ?>" data-type="<?= $modelUser->type ?>">Контакты</a>
    </div>
  </div>
</div>

frontend/views/model/_section-instagram.php
<div class="gallery-meta" data-for="instagram" data-only-image="1">
  <div class="_imagesCount"><?= sizeof($model->instagramImages) ?></div>

  <div class="meta-images">
    <?php foreach ($model->instagramImages as $key => $image): ?>
      <div data-position="<?= $key ?>" data-id="<?= $image->id ?>" data-src="<?= $image->imageWithPath ?>"></div>
    <?php endforeach; ?>
  </div>
</div>


<section class="model__content" id="instagram">
  <div class="container">

    <div class="model__section">

      <div class="social-title">
        <div>
          <div class="title">Инстаграм</div>
          <div class="feed-info">Здесь отображается лента Instagram</div>
        </div>


        <?php if ($isProfile): ?>
          <?php $link = $model->user->hasInstagramToken() ? '/profile/instagram' : '/profile/edit?scrollTo=instagram'; ?>
          <a href="<?= $link ?>" class="btn border-btn">Изменить</a>
        <?php else: ?>
          <?php if ($model->instagramCount > 0): ?>
            <div class="instagram-count">
              <div class="ico">
                <svg _ngcontent-c34="" class="icon" height="18" viewBox="0 0 18 18" width="18" xmlns="http://www.w3.org/2000/svg"><path _ngcontent-c34="" d="M5.54 1.077A4.545 4.545 0 0 0 1 5.617v6.92a4.545 4.545 0 0 0 4.54 4.54h6.92a4.545 4.545 0 0 0 4.54-4.54v-6.92a4.545 4.545 0 0 0-4.54-4.54H5.54zm0 1.298h6.92a3.222 3.222 0 0 1 3.243 3.243v6.919a3.222 3.222 0 0 1-3.244 3.243H5.541a3.222 3.222 0 0 1-3.244-3.243v-6.92a3.222 3.222 0 0 1 3.244-3.242zm7.784 1.297a.865.865 0 1 0 0 1.73.865.865 0 0 0 0-1.73zM9 4.752a4.334 4.334 0 0 0-4.324 4.325A4.334 4.334 0 0 0 9 13.402a4.334 4.334 0 0 0 4.324-4.325A4.334 4.334 0 0 0 9 4.753zM9 6.05a3.017 3.017 0 0 1 3.027 3.027A3.017 3.017 0 0 1 9 12.104a3.017 3.017 0 0 1-3.027-3.027A3.017 3.017 0 0 1 9 6.05z" fill="currentColor" fill-rule="nonzero"></path></svg>
              </div>
              <div class="value <?= (!empty($model->instagram) AND !is_null($model->instagram)) ? 'js-instagram-followers' : '' ?>" data-id="<?= $model->id ?>" data-instagram="<?= $model->instagram ?>">
                <?= (!empty($model->instagramCount) AND !is_null($model->instagramCount)) ? $model->instagramCount : '-' ?>
              </div>
              <div class="subtitle">followers</div>
            </div>
          <?php endif; ?>
        <?php endif; ?>
      </div>

      <div class="card _images _social">


        <?php foreach ($model->instagramImages as $key => $image): ?>
          <div class="model__image js-open-gallery"
               data-for="instagram"
               data-position="<?= $key ?>"
          >
            <img data-src="<?= $image->imageWithPath ?>" class="lazyload" />
          </div>
        <?php endforeach; ?>


          <!-- <div class="instagram-plug">
            <span>Загрузка...</span>
          </div> -->



        <?php if ($isProtected): ?>
          <?= $this->render('_protected') ?>
        <?php endif; ?>

      </div>

    </div>

  </div>
</section>

frontend/views/model/_section-portfolio.php
<div class="gallery-meta" data-for="images" data-only-image="1">
  <div class="_imagesCount"><?= sizeof($model->images) ?></div>

  <div class="meta-images">
    <?php foreach ($model->images as $key => $image): ?>
      <div data-position="<?= $key ?>" data-id="<?= $image->id ?>" data-src="<?= $image->imageThumbWithPath ?>"></div>
    <?php endforeach; ?>
  </div>
</div>

<section class="model__content" id="portfolio">
  <div class="container">

    <div class="model__section">

      <div class="model__section-title"><span>Портфолио</span></div>

      <div class="card _images">

        <?php foreach ($model->images as $key => $image): ?>
          <div class="model__image js-open-gallery"
               data-for="images"
               data-position="<?= $key ?>"
          >
            <img data-src="<?= $image->imageThumbWithPath ?>" class="lazyload" />
            <?php if ($isProfile): ?>
              <a href="#" class="img-remove-btn js-remove-img-btn" data-id="<?= $image->id ?>">х</a>
            <?php endif; ?>
          </div>
        <?php endforeach; ?>

        <?php if ($isProfile): ?>
          <!-- <input type="file" name="Model[images][]" class="hidden js-profile-images-file-input" multiple accept="image/*">
          <div class="model__image add-photo-item js-file-btn _add" data-for="Model[images][]"><img src="/img/plus.png" alt="plus"></div> -->
          <a href="/profile/edit?scrollTo=portfolio" class="model__image add-photo-item _add"><img class="plus" src="/img/plus.png" alt="plus"></a>

        <?php endif; ?>


      </div>

    </div>

  </div>
</section>

frontend/views/model/_success-send-request.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use common\models\User;
?>

<div class="contact-data">

  <div class="contact-request">
    <p>Ваш запрос успешно отправлен! В ближайшее время владелец этого аккаунта решит предоставлять ли Вам доступ к его данным и мы уведомим Вас об его решении.</p>
  </div>
</div>