common/models/Model.php
<?php

namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use yii\imagine\Image;
use Imagine\Image\ManipulatorInterface;

class Model extends ActiveRecord
{
    public $avatarFile;
    public $digitFile_1;
    public $digitFile_2;
    public $digitFile_3;
    public $digitFile_4;

    public static function tableName()
    {
        return '{{%model}}';
    }

    public function rules()
    {
        return [
            [['avatarFile'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
            [['digitFile_1'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
            [['digitFile_2'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
            [['digitFile_3'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
            [['digitFile_4'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
            [['avatar', 'city', 'instagram', 'phone', 'telegram', 'whatsapp', 'video', 'digit_1', 'digit_2', 'digit_3', 'digit_4'], 'string', 'max' => 255],
            [['pastClients'], 'string'],
            [[
              'userId',
              'categoryId',
              'gender',
              'hourPrice',
              'dayPrice',
              'age',
              'height',
              'weight',
              'shoes',
              'shirt',
              'bust',
              'ethnicity',
              'eyes',
              'hair',
              'tattoo',
              'isHiddenContacts',
              'tfp',
            ], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'userId' => 'Пользователь',
            'avatar' => 'Аватар',
            'categoryId' => 'Категория',
            'city' => 'Город',
            'gender' => 'Пол',
            'hourPrice' => 'Стоимость часа',
            'dayPrice' => 'Стоимость дня',
            'age' => 'Возраст',
            'height' => 'Рост',
            'weight' => 'Вес',
            'shoes' => 'Размер обуви',
            'shirt' => 'Размер одежды',
            'bust' => 'Размер груди',
            'ethnicity' => 'Тип лица',
            'eyes' => 'Цвет глаз',
            'hair' => 'Цвет волос',
            'tattoo' => 'Татуировки',
            'instagram' => 'Инстаграм',
            'phone' => 'Телефон',
            'telegram' => 'Телеграм',
            'whatsapp' => 'Whatsapp',
            'video' => 'Промо видео',
            'pastClients' => 'Последние места работы',
            'isHiddenContacts' => 'Скрыть ваши контакты?',
            'tfp' => 'Возможно ли TFP?',
        ];
    }


    private function checkDir($path = false)
    {
      $dir = Yii::getAlias('@upload/') . $this->userId;

      if ($path) {
        $dir .= '/' . $path;
      }

      if(!is_dir($dir)) {
        mkdir($dir, 0777, true);
      }
    }


    public function uploadAvatar()
    {
      if (is_object($this->avatarFile)) {
        $fileName = Yii::$app->security->generateRandomString(12) . '.' . $this->avatarFile->extension;

        $this->avatar = $fileName;

        $path = '@upload/';
        $imagePath = Yii::getAlias($path . 'all/' . $fileName);

        if ($this->avatarFile->saveAs($imagePath)) {
            // Yii::$app->imageOptimizer->optimize($imagePath);
            Yii::$app->imageOptimizer->deleteEXIFMetadata($imagePath);
        }

        $avatarPath = Yii::getAlias($path . 'avatars/' . $fileName); // 342x204

        if (Image::thumbnail($imagePath, 180, 180, ManipulatorInterface::THUMBNAIL_OUTBOUND)->save($avatarPath, ['quality' => 81])) {
            // Yii::$app->imageOptimizer->optimize($avatarPath);
        }

        return true;
      } else {
        return false;
      }
    }

    public function uploadDigits()
    {
      $digitFiles = [
        $this->digitFile_1,
        $this->digitFile_2,
        $this->digitFile_3,
        $this->digitFile_4,
      ];


      $this->checkDir();
      $this->checkDir('digits');

      if (is_array($digitFiles)) {
        foreach ($digitFiles as $key => $digitFile) {
          if (is_object($digitFile)) {
            $fileName = Yii::$app->security->generateRandomString(12) . '.' . $digitFile->extension;

            if ($key == 0) { $this->digit_1 = $fileName; }
            else if ($key == 1) { $this->digit_2 = $fileName; }
            else if ($key == 2) { $this->digit_3 = $fileName; }
            else if ($key == 3) { $this->digit_4 = $fileName; }

            $path = '@upload/' . $this->userId;
            $imagePath = Yii::getAlias($path . '/digits/' . $fileName);

            if ($digitFile->saveAs($imagePath)) {
                // Yii::$app->imageOptimizer->optimize($imagePath);
                Yii::$app->imageOptimizer->deleteEXIFMetadata($imagePath);
            }

          }
        }



        return true;
      } else {
        return false;
      }
    }

    public function getAvatarImage()
    {
      if(!is_null($this->avatar) AND !empty($this->avatar)) {
        return Yii::getAlias('/upload/avatars/' . $this->avatar);;
      }
      return '/img/placeholder@2x.png';
    }

    public function getDigit1Image()
    {
      if(!is_null($this->digit_1) AND !empty($this->digit_1)) {
        return Yii::getAlias('/upload/'.$this->userId.'/digits/' . $this->digit_1);;
      }
      return '/img/digit_1.jpg';
    }
    public function getDigit2Image()
    {
      if(!is_null($this->digit_2) AND !empty($this->digit_2)) {
        return Yii::getAlias('/upload/'.$this->userId.'/digits/' . $this->digit_2);;
      }
      return '/img/digit_2.jpg';
    }
    public function getDigit3Image()
    {
      if(!is_null($this->digit_3) AND !empty($this->digit_3)) {
        return Yii::getAlias('/upload/'.$this->userId.'/digits/' . $this->digit_3);;
      }
      return '/img/digit_3.jpg';
    }
    public function getDigit4Image()
    {
      if(!is_null($this->digit_4) AND !empty($this->digit_4)) {
        return Yii::getAlias('/upload/'.$this->userId.'/digits/' . $this->digit_4);;
      }
      return '/img/digit_4.jpg';
    }

    public function getImages()
    {
        return $this->hasMany(ModelImage::className(), ['modelId' => 'id']);
    }

    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'userId']);
    }

    public function getInstagramImages()
    {
        return $this->hasMany(InstagramImage::className(), ['userId' => 'userId']);
    }


    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created',
                'updatedAtAttribute' => 'updated',
                'value' => new Expression('NOW()'),
            ],
        ];
    }
}

common/models/ModelImage.php
<?php

namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use yii\imagine\Image;
use Imagine\Image\ManipulatorInterface;

class ModelImage extends ActiveRecord
{

    public static function tableName()
    {
        return '{{%model_image}}';
    }

    public function rules()
    {
        return [
            [['image'], 'string', 'max' => 255],
            [['modelId'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'modelId' => 'Модель',
            'image' => 'Изображение',
        ];
    }

    public function getModel()
    {
        return $this->hasOne(Model::className(), ['id' => 'modelId']);
    }

    public function getImageWithPath()
    {
      return '/upload/'.$this->model->userId.'/' . $this->image;
      // return Yii::getAlias('@upload/all/' . $this->image);
    }

    public function getImageThumbWithPath()
    {
      return '/upload/'.$this->model->userId.'/thumbnails/' . $this->image;
      // return Yii::getAlias('@upload/all/' . $this->image);
    }


    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created',
                'updatedAtAttribute' => 'updated',
                'value' => new Expression('NOW()'),
            ],
        ];
    }
}

frontend/controllers/BrowseController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\data\ActiveDataProvider;
use yii\db\Expression;
use common\models\User;
use common\models\Model;
use common\models\Photographer;
use common\models\ModelImage;

class BrowseController extends Controller
{

    public function actionIndex()
    {
      $query = Model::find()->leftJoin('user', 'user.id = model.userId')
        ->where(['user.status' => User::STATUS_ACTIVE]);

      if (isset($_GET['search']) AND !empty($_GET['search'])) {
          $str = explode(' ', $_GET['search']);
          if (sizeof($str) == 2) {
            $query->andWhere(['OR',
              ['LIKE', 'user.name', '%'.$str[0].'%', false],
              ['LIKE', 'user.surname', '%'.$str[0].'%', false],
              ['LIKE', 'user.name', '%'.$str[1].'%', false],
              ['LIKE', 'user.surname', '%'.$str[1].'%', false]
            ]);
          } else {
            $query->andWhere(['OR',
              ['LIKE', 'user.name', '%'.$str[0].'%', false],
              ['LIKE', 'user.surname', '%'.$str[0].'%', false]
            ]);
          }
      }

      if (isset($_GET['categoryId']) AND !empty($_GET['categoryId'])) {
        $query->andWhere(['model.categoryId' => $_GET['categoryId']]);
      }

      if (isset($_GET['gender']) AND !empty($_GET['gender'])) {
        $query->andWhere(['IN', 'model.gender', $_GET['gender']]);
      }

      if (isset($_GET['city']) AND !empty($_GET['city']) AND $_GET['city'] != 'any') {
        $query->andWhere(['model.city' => $_GET['city']]);
      }

      if (isset($_GET['hourPrice']['min']) AND !empty($_GET['hourPrice']['min']) AND isset($_GET['hourPrice']['max']) AND !empty($_GET['hourPrice']['max'])) {
        $query->andWhere(['>=', 'model.hourPrice', $_GET['hourPrice']['min']])
              ->andWhere(['<=', 'model.hourPrice', $_GET['hourPrice']['max']]);
      }

      if (isset($_GET['tfp']) AND !empty($_GET['tfp'])) {
        $query->andWhere(['IN', 'model.tfp', $_GET['tfp']]);
      }


      if (isset($_GET['height']['min']) AND !empty($_GET['height']['min']) AND isset($_GET['height']['max']) AND !empty($_GET['height']['max'])) {
        $query->andWhere(['>=', 'model.height', $_GET['height']['min']])
              ->andWhere(['<=', 'model.height', $_GET['height']['max']]);
      }
      if (isset($_GET['weight']['min']) AND !empty($_GET['weight']['min']) AND isset($_GET['weight']['max']) AND !empty($_GET['weight']['max'])) {
        $query->andWhere(['>=', 'model.weight', $_GET['weight']['min']])
              ->andWhere(['<=', 'model.weight', $_GET['weight']['max']]);
      }
      if (isset($_GET['shirt']['min']) AND !empty($_GET['shirt']['min']) AND isset($_GET['shirt']['max']) AND !empty($_GET['shirt']['max'])) {
        $query->andWhere(['>=', 'model.shirt', $_GET['shirt']['min']])
              ->andWhere(['<=', 'model.shirt', $_GET['shirt']['max']]);
      }
      if (isset($_GET['shoes']['min']) AND !empty($_GET['shoes']['min']) AND isset($_GET['shoes']['max']) AND !empty($_GET['shoes']['max'])) {
        $query->andWhere(['>=', 'model.shoes', $_GET['shoes']['min']])
              ->andWhere(['<=', 'model.shoes', $_GET['shoes']['max']]);
      }
      if (isset($_GET['bust']['min']) AND !empty($_GET['bust']['min']) AND isset($_GET['bust']['max']) AND !empty($_GET['bust']['max'])) {
        $query->andWhere(['>=', 'model.bust', $_GET['bust']['min']])
              ->andWhere(['<=', 'model.bust', $_GET['bust']['max']]);
      }
      if (isset($_GET['age']['min']) AND !empty($_GET['age']['min']) AND isset($_GET['age']['max']) AND !empty($_GET['age']['max'])) {
        $query->andWhere(['>=', 'model.age', $_GET['age']['min']])
              ->andWhere(['<=', 'model.age', $_GET['age']['max']]);
      }


      if (isset($_GET['ethnicity']) AND !empty($_GET['ethnicity'])) {
        $query->andWhere(['IN', 'model.ethnicity', $_GET['ethnicity']]);
      }
      if (isset($_GET['eye']) AND !empty($_GET['eye'])) {
        $query->andWhere(['IN', 'model.eyes', $_GET['eye']]);
      }
      if (isset($_GET['hair']) AND !empty($_GET['hair'])) {
        $query->andWhere(['IN', 'model.hair', $_GET['hair']]);
      }
      if (isset($_GET['tattoo']) AND !empty($_GET['tattoo'])) {
        $query->andWhere(['IN', 'model.tattoo', $_GET['tattoo']]);
      }



      $dataProvider = new ActiveDataProvider([
          'query' => $query,
          'pagination' => [
              'pageSize' => 40,
          ],
      ]);

      return $this->render('index', [
        'dataProvider' => $dataProvider,
      ]);
    }



    public function actionPhotographers()
    {
      $query = Photographer::find()->leftJoin('user', 'user.id = photographer.userId')
        ->where(['user.status' => User::STATUS_ACTIVE]);

        if (isset($_GET['search']) AND !empty($_GET['search'])) {
            $str = explode(' ', $_GET['search']);
            if (sizeof($str) == 2) {
              $query->andWhere(['OR',
                ['LIKE', 'user.name', '%'.$str[0].'%', false],
                ['LIKE', 'user.surname', '%'.$str[0].'%', false],
                ['LIKE', 'user.name', '%'.$str[1].'%', false],
                ['LIKE', 'user.surname', '%'.$str[1].'%', false]
              ]);
            } else {
              $query->andWhere(['OR',
                ['LIKE', 'user.name', '%'.$str[0].'%', false],
                ['LIKE', 'user.surname', '%'.$str[0].'%', false]
              ]);
            }
        }

      if (isset($_GET['categoryId']) AND !empty($_GET['categoryId'])) {
        $query->andWhere(['photographer.categoryId' => $_GET['categoryId']]);
      }

      if (isset($_GET['gender']) AND !empty($_GET['gender'])) {
        $query->andWhere(['IN', 'photographer.gender', $_GET['gender']]);
      }

      if (isset($_GET['city']) AND !empty($_GET['city']) AND $_GET['city'] != 'any') {
        $query->andWhere(['photographer.city' => $_GET['city']]);
      }

      if (isset($_GET['tfp']) AND !empty($_GET['tfp'])) {
        $query->andWhere(['IN', 'photographer.tfp', $_GET['tfp']]);
      }

      if (isset($_GET['hourPrice']['min']) AND !empty($_GET['hourPrice']['min']) AND isset($_GET['hourPrice']['max']) AND !empty($_GET['hourPrice']['max'])) {
        $query->andWhere(['>=', 'photographer.hourPrice', $_GET['hourPrice']['min']])
              ->andWhere(['<=', 'photographer.hourPrice', $_GET['hourPrice']['max']]);
      }


      $dataProvider = new ActiveDataProvider([
          'query' => $query,
          'pagination' => [
              'pageSize' => 40,
          ],
      ]);

      return $this->render('photographers', [
        'dataProvider' => $dataProvider,
      ]);
    }


    public function actionLocations()
    {
      return $this->render('locations');
    }


    public function actionOptimizeImages()
    {
      $dir = Yii::getAlias('@upload');
      $files = $this->get_dir_files($dir);


      foreach ($files as $key => $file) {
        Yii::$app->imageOptimizer->optimize($file);
      }

      // test($files);
      die;
    }



    private function get_dir_files( $dir, $recursive = true, $include_folders = false ){
    	if( ! is_dir($dir) )
    		return array();

    	$files = array();

    	$dir = rtrim( $dir, '/\\' ); // удалим слэш на конце

    	foreach( glob( "$dir/{,.}[!.,!..]*", GLOB_BRACE ) as $file ){

    		if( is_dir( $file ) ){
    			if( $include_folders )
    				$files[] = $file;
    			if( $recursive )
    				$files = array_merge( $files, $this->get_dir_files($file, $recursive, $include_folders ) );
    		}
    		else
    			$files[] = $file;
    	}

    	return $files;
    }

}

frontend/views/browse/_model-item.php
<?php
use common\models\Data;
use common\models\User;
use common\helpers\FormatHelper;

$modelUser = $model->user;
$modelName = $modelUser->name . ' ' . $modelUser->surname;
?>

<div class="model-item">
  <div class="model-item__content">

    <header class="model-item__header">
      <a href="/model/<?= $model->id ?>" title="<?= $modelName ?>" class="avatar">
        <div class="img" style="background-image: url(<?= $model->avatarImage ?>);background-position: center;background-size: cover;"></div>
      </a>
      <div class="main-details">
        <div class="main-details__top">
          <a href="/model/<?= $model->id ?>" title="<?= $modelName ?>" class="name"><?= $modelName ?></a>
          <a href="#" class="favorite js-favorite-btn" data-id="<?= $model->id ?>" data-type="<?= User::TYPE_MODEL ?>">
            <svg class="Icon__icon--2u9lI" xmlns="http://www.w3.org/2000/svg" width="21" height="18" viewBox="0 0 20 18"><g fill-rule="nonzero" fill="none"><path fill="#222" fill-opacity=".09" fill-rule="evenodd" stroke="currentColor" stroke-opacity=".15" d="M10 3.087c1.612-1.803 4.088-2.5 6.25-1.85C18.531 1.923 20 3.94 20 6.816c0 1.447-.547 2.903-1.563 4.353-.859 1.227-2.03 2.417-3.437 3.555a30.715 30.715 0 0 1-3.438 2.397c-.41.248-.792.466-1.132.652l-.195.105-.235.125-.235-.125a29.68 29.68 0 0 1-1.328-.757A30.72 30.72 0 0 1 5 14.724c-1.406-1.138-2.578-2.328-3.438-3.555C.547 9.72 0 8.263 0 6.816 0 3.94 1.469 1.923 3.75 1.237c2.162-.65 4.638.047 6.25 1.85z"></path></g></svg>
          </a>
        </div>
        <div class="main-details__location">
          <?= Data::CITIES[ $model->city ] ?>
        </div>
      </div>
    </header>

    <div class="model-item__info">
      <div class="info-item">
        <div class="value"><?= FormatHelper::price($model->hourPrice, 0, '₽') ?></div>
        <div class="title">В час</div>
      </div>
      <div class="info-item">
        <div class="value"><?= FormatHelper::price($model->dayPrice, 0, '₽') ?></div>
        <div class="title">В день</div>
      </div>
      <div class="info-item">
        <div class="value">
          <div class="ico">
            <svg class="Icon__icon--2u9lI" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18"><path fill="currentColor" fill-rule="nonzero" d="M5.54 1.077A4.545 4.545 0 0 0 1 5.617v6.92a4.545 4.545 0 0 0 4.54 4.54h6.92a4.545 4.545 0 0 0 4.54-4.54v-6.92a4.545 4.545 0 0 0-4.54-4.54H5.54zm0 1.298h6.92a3.222 3.222 0 0 1 3.243 3.243v6.919a3.222 3.222 0 0 1-3.244 3.243H5.541a3.222 3.222 0 0 1-3.244-3.243v-6.92a3.222 3.222 0 0 1 3.244-3.242zm7.784 1.297a.865.865 0 1 0 0 1.73.865.865 0 0 0 0-1.73zM9 4.752a4.334 4.334 0 0 0-4.324 4.325A4.334 4.334 0 0 0 9 13.402a4.334 4.334 0 0 0 4.324-4.325A4.334 4.334 0 0 0 9 4.753zM9 6.05a3.017 3.017 0 0 1 3.027 3.027A3.017 3.017 0 0 1 9 12.104a3.017 3.017 0 0 1-3.027-3.027A3.017 3.017 0 0 1 9 6.05z"></path></svg>
          </div>
          <span class="<?= (!empty($model->instagram) AND !is_null($model->instagram)) ? 'js-instagram-followers' : '' ?>" data-id="<?= $model->id ?>" data-instagram="<?= $model->instagram ?>">
            <?= (!empty($model->instagramCount) AND !is_null($model->instagramCount)) ? $model->instagramCount : '-' ?>
          </span>
        </div>
        <div class="title">Подписчиков</div>
      </div>
    </div>

    <div class="model-item__actions">
      <a href="/model/<?= $model->id ?>" title="<?= $modelName ?>" class="btn border-btn">Портфолио</a>
      <a href="#" class="btn js-show-contact" data-id="<?= $model->id ?>" data-type="<?= User::TYPE_MODEL ?>">Контакты</a>
    </div>

  </div>
  <div class="model-item__photos">

    <div class="gallery-meta" data-for="model-<?= $model->id ?>">
      <div class="_id"><?= $model->id ?></div>
      <div class="_name"><?= $modelName ?></div>
      <div class="_price"><?= FormatHelper::price($model->hourPrice, 0, '₽') ?>/час • <?= FormatHelper::price($model->dayPrice, 0, '₽') ?>/день</div>
      <div class="_location"><?= Data::CITIES[ $model->city ] ?></div>
      <div class="_imagesCount"><?= sizeof($model->images) ?></div>
      <div class="meta-params">
        <div class="_height"><?= $model->height ?>см.</div>
        <div class="_weight"><?= $model->weight ?>кг.</div>
        <div class="_age"><?= $model->age ?></div>
        <div class="_shoes"><?= $model->shoes ?></div>
        <div class="_shirt"><?= $model->shirt ?></div>
        <div class="_bust"><?= $model->bust ?></div>
        <div class="_ethnicity"><?= Data::ETHNICITY[ $model->ethnicity ] ?></div>
        <div class="_eyes"><?= Data::EYES[ $model->eyes ] ?></div>
        <div class="_hair"><?= Data::HAIR[ $model->hair ] ?></div>
        <div class="_tattoo"><?= Data::TATTOO[ $model->tattoo ] ?></div>
      </div>
      <div class="meta-images">
        <?php foreach ($model->images as $key => $image): ?>
          <div data-position="<?= $key ?>" data-id="<?= $image->id ?>" data-src="<?= $image->imageThumbWithPath ?>"></div>
        <?php endforeach; ?>
      </div>
    </div>


    <?php $counter = 0; ?>
    <?php foreach ($model->images as $key => $image): ?>
      <?php if ($counter > 3) { break; } ?>
      <div class="model-item__photo js-open-gallery" data-for="model-<?= $model->id ?>" data-position="<?= $key ?>">
        <div class="overlay">
          <div class="ico">
            <svg class="Icon__icon--2u9lI" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 33 20"><g fill="none" fill-rule="evenodd"><ellipse cx="16.4" cy="10" stroke="currentColor" stroke-width="2.592" rx="3.785" ry="3.75"></ellipse><ellipse cx="15.138" cy="8.75" fill="currentColor" fill-rule="nonzero" rx="1.262" ry="1.25"></ellipse><path fill="currentColor" d="M0 10l2.068-1.577L4.138 10l2.622 2.003 3.486 2.653a10.166 10.166 0 0 0 12.308 0l4.046-3.084 2.07 1.577-4.579 3.489a12.706 12.706 0 0 1-15.382 0l-6.64-5.06L0 10zm30.732 1.577L32.8 10l-2.068-1.577-6.64-5.06a12.706 12.706 0 0 0-15.383 0L4.134 6.85l2.07 1.577 4.042-3.082a10.167 10.167 0 0 1 12.308 0l3.835 2.913L28.662 10l2.07 1.577z"></path></g></svg>
          </div>
          <span class="text">Быстрый просмотр</span>
        </div>
        <div class="photo">
          <img data-src="<?= $image->imageThumbWithPath ?>" class="lazyload" />
        </div>
      </div>
      <?php $counter++; ?>
    <?php endforeach; ?>



  </div>
</div>

frontend/views/browse/index.php
<?php
use common\models\Data;
use yii\widgets\ListView;

$this->title = 'Modelista - модели';
$this->params['class'] = 'browse';
?>

<?= $this->render('_filter-model') ?>


<section class="categories">
  <div class="container">

    <div class="categories__scroll">

      <?php foreach (Data::CATEGORIES as $key => $cat): ?>
        <a href="/browse?categoryId=<?= $key ?>" class="category-item">
          <div class="category-item__img">
            <div class="img" style="background-image: url(/img/categories/<?= $cat['image'] ?>);background-position: center;background-size: cover;"></div>
          </div>
          <h3 class="category-item__title"><?= $cat['title'] ?></h3>
        </a>
      <?php endforeach; ?>

    </div>

  </div>
</section>


<section>
  <div class="container">

    <?= ListView::widget([
      'dataProvider' => $dataProvider,
      'itemView' => '_model-item',
      'emptyText' => 'К сожалению, ничего не найдено...',
    ]) ?>

  </div>
</section>

frontend/views/browse/locations.php
<?php
use common\models\Data;
use yii\widgets\ListView;

$this->title = 'Modelista - места';
$this->params['class'] = 'browse';
?>

<section>
  <div class="container">

    <br>
    <br>
    <div class="empty">
      Временно недоступно...
    </div>

  </div>
</section>

frontend/views/browse/photographers.php
<?php
use common\models\Data;
use yii\widgets\ListView;

$this->title = 'Modelista - фотографы';
$this->params['class'] = 'browse';
?>

<?= $this->render('_filter-photographer') ?>


<section class="categories">
  <div class="container">

    <div class="categories__scroll">

      <?php foreach (Data::CATEGORIES as $key => $cat): ?>
        <a href="/browse?categoryId=<?= $key ?>" class="category-item">
          <div class="category-item__img">
            <div class="img" style="background-image: url(/img/categories/<?= $cat['image'] ?>);background-position: center;background-size: cover;"></div>
          </div>
          <h3 class="category-item__title"><?= $cat['title'] ?></h3>
        </a>
      <?php endforeach; ?>

    </div>

  </div>
</section>


<section>
  <div class="container">

    <?= ListView::widget([
      'dataProvider' => $dataProvider,
      'itemView' => '_photographer-item',
      'emptyText' => 'К сожалению, ничего не найдено...',
    ]) ?>

  </div>
</section>